// Auto-generated by OpenLane
module Slave(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[7:0] data_in,
  input clkin,
  input reset,
  input slave_select_in,
  input sclk,
  input sdi,
  output[7:0] data_out,
  output sdo
);
endmodule
