// Auto-generated by OpenLane
module Master(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[7:0] data_in,
  input[1:0] slave_select_in,
  input[1:0] mode,
  input clkin,
  input reset,
  input tx_enable,
  input miso,
  output[7:0] data_out,
  output sclk,
  output mosi,
  output[3:0] slave_select
);
endmodule
