/* Generated by Yosys 0.65 (git sha1 90c26fe6714b441363d2ddb47a6d646b8868ff5d, g++ 16.1.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "src/Slave.v:5.1-124.10" *)
module Slave(data_in, clkin, reset, slave_select_in, sclk, sdi, data_out, sdo);
  (* src = "src/Slave.v:6.22-6.29" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "src/Slave.v:7.16-7.21" *)
  input clkin;
  wire clkin;
  (* src = "src/Slave.v:7.23-7.28" *)
  input reset;
  wire reset;
  (* src = "src/Slave.v:8.16-8.31" *)
  input slave_select_in;
  wire slave_select_in;
  (* src = "src/Slave.v:8.33-8.37" *)
  input sclk;
  wire sclk;
  (* src = "src/Slave.v:8.39-8.42" *)
  input sdi;
  wire sdi;
  (* src = "src/Slave.v:9.22-9.30" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "src/Slave.v:10.16-10.19" *)
  output sdo;
  wire sdo;
  (* src = "src/Slave.v:22.1-64.4" *)
  wire [2:0] _000_;
  (* src = "src/Slave.v:22.1-64.4" *)
  wire [1:0] _001_;
  (* src = "src/Slave.v:67.1-101.8" *)
  wire [2:0] _002_;
  (* src = "src/Slave.v:67.1-101.8" *)
  wire [1:0] _003_;
  (* src = "src/Slave.v:67.1-101.8" *)
  wire _004_;
  (* src = "src/Slave.v:105.1-123.4" *)
  wire [7:0] _005_;
  (* src = "src/Slave.v:67.1-101.8" *)
  wire [7:0] _006_;
  (* src = "src/Slave.v:67.1-101.8" *)
  wire [2:0] _007_;
  (* src = "src/Slave.v:67.1-101.8" *)
  wire [1:0] _008_;
  (* src = "src/Slave.v:67.1-101.8" *)
  wire _009_;
  (* src = "src/Slave.v:105.1-123.4" *)
  wire [7:0] _010_;
  (* src = "src/Slave.v:67.1-101.8" *)
  wire [7:0] _011_;
  (* src = "src/Slave.v:67.1-101.8" *)
  wire [1:0] _012_;
  (* src = "src/Slave.v:115.12-115.20" *)
  wire _013_;
  (* src = "src/Slave.v:78.12-78.20" *)
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire [1:0] _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire [1:0] _042_;
  wire [1:0] _043_;
  wire [15:0] _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire [2:0] _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  (* src = "src/Slave.v:115.12-115.15" *)
  wire _105_;
  (* src = "src/Slave.v:78.15-78.20" *)
  wire _106_;
  wire [1:0] _107_;
  wire _108_;
  wire [2:0] _109_;
  wire [7:0] _110_;
  (* force_downto = 32'd1 *)
  (* src = "src/Slave.v:90.20-90.35|/usr/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _111_;
  (* force_downto = 32'd1 *)
  (* src = "src/Slave.v:89.35-89.48|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _112_;
  (* force_downto = 32'd1 *)
  (* src = "src/Slave.v:89.35-89.48|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _113_;
  (* src = "src/Slave.v:89.35-89.48|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _114_;
  (* src = "src/Slave.v:20.11-20.22" *)
  reg [2:0] datacounter;
  (* src = "src/Slave.v:20.24-20.39" *)
  wire [2:0] datacounternext;
  (* src = "src/Slave.v:21.29-21.42" *)
  wire [1:0] mode_internal;
  (* src = "src/Slave.v:21.18-21.27" *)
  wire [1:0] nextstate;
  (* src = "src/Slave.v:18.5-18.7" *)
  reg rx;
  (* src = "src/Slave.v:19.41-19.52" *)
  reg [7:0] shiftreg_rx;
  (* src = "src/Slave.v:19.11-19.22" *)
  reg [7:0] shiftreg_tx;
  (* src = "src/Slave.v:19.54-19.69" *)
  wire [7:0] shiftregnext_rx;
  (* src = "src/Slave.v:19.24-19.39" *)
  wire [7:0] shiftregnext_tx;
  (* src = "src/Slave.v:21.11-21.16" *)
  reg [1:0] state;
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_tx[0] <= 1'h0;
    else if (_028_) shiftreg_tx[0] <= _110_[0];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_tx[1] <= 1'h0;
    else if (_028_) shiftreg_tx[1] <= _110_[1];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_tx[2] <= 1'h0;
    else if (_028_) shiftreg_tx[2] <= _110_[2];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_tx[3] <= 1'h0;
    else if (_028_) shiftreg_tx[3] <= _110_[3];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_tx[4] <= 1'h0;
    else if (_028_) shiftreg_tx[4] <= _110_[4];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_tx[5] <= 1'h0;
    else if (_028_) shiftreg_tx[5] <= _110_[5];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_tx[6] <= 1'h0;
    else if (_028_) shiftreg_tx[6] <= _110_[6];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_tx[7] <= 1'h0;
    else if (_028_) shiftreg_tx[7] <= _110_[7];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[0] <= 1'h0;
    else if (_027_) data_out[0] <= shiftreg_rx[0];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[1] <= 1'h0;
    else if (_027_) data_out[1] <= shiftreg_rx[1];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[2] <= 1'h0;
    else if (_027_) data_out[2] <= shiftreg_rx[2];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[3] <= 1'h0;
    else if (_027_) data_out[3] <= shiftreg_rx[3];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[4] <= 1'h0;
    else if (_027_) data_out[4] <= shiftreg_rx[4];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[5] <= 1'h0;
    else if (_027_) data_out[5] <= shiftreg_rx[5];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[6] <= 1'h0;
    else if (_027_) data_out[6] <= shiftreg_rx[6];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[7] <= 1'h0;
    else if (_027_) data_out[7] <= shiftreg_rx[7];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[0] <= 1'h0;
    else if (_026_) shiftreg_rx[0] <= shiftregnext_rx[0];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[1] <= 1'h0;
    else if (_026_) shiftreg_rx[1] <= shiftregnext_rx[1];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[2] <= 1'h0;
    else if (_026_) shiftreg_rx[2] <= shiftregnext_rx[2];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[3] <= 1'h0;
    else if (_026_) shiftreg_rx[3] <= shiftregnext_rx[3];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[4] <= 1'h0;
    else if (_026_) shiftreg_rx[4] <= shiftregnext_rx[4];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[5] <= 1'h0;
    else if (_026_) shiftreg_rx[5] <= shiftregnext_rx[5];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[6] <= 1'h0;
    else if (_026_) shiftreg_rx[6] <= shiftregnext_rx[6];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[7] <= 1'h0;
    else if (_026_) shiftreg_rx[7] <= shiftregnext_rx[7];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) datacounter[0] <= 1'h1;
    else if (_025_) datacounter[0] <= _000_[0];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) datacounter[1] <= 1'h1;
    else if (_025_) datacounter[1] <= _000_[1];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) datacounter[2] <= 1'h1;
    else if (_025_) datacounter[2] <= _000_[2];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) state[0] <= 1'h0;
    else if (_024_) state[0] <= _001_[0];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) state[1] <= 1'h0;
    else if (_024_) state[1] <= _001_[1];
  (* src = "src/Slave.v:22.1-64.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) rx <= 1'h0;
    else rx <= sclk;
  assign _111_[0] = ~datacounter[0];
  assign _111_[2] = ~datacounter[2];
  assign _111_[1] = ~datacounter[1];
  assign _031_ = ~state[1];
  assign _032_ = ~state[0];
  assign _033_ = ~reset;
  assign _034_ = ~_029_;
  assign _112_[1] = datacounter[1] |(* src = "src/Slave.v:89.35-89.48|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _114_;
  assign _114_ = _111_[1] &(* src = "src/Slave.v:89.35-89.48|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  datacounter[0];
  assign _014_ = rx &(* src = "src/Slave.v:78.12-78.20" *)  _106_;
  assign _013_ = _105_ &(* src = "src/Slave.v:115.12-115.20" *)  sclk;
  assign _113_[1] = _111_[1] ^(* src = "src/Slave.v:89.35-89.48|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  datacounter[0];
  assign _113_[2] = _111_[2] ^(* src = "src/Slave.v:89.35-89.48|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  _112_[1];
  assign _036_ = _023_ & _022_;
  assign _028_ = _036_ & _030_;
  assign _023_ = _037_ | _014_;
  assign _027_ = _030_ & _108_;
  assign _038_[0] = _030_ & _021_;
  assign _038_[1] = _020_ & _022_;
  assign _026_ = _038_[0] & _038_[1];
  assign _039_ = _033_ | _067_[1];
  assign _021_ = _039_ | _067_[2];
  assign _040_ = _033_ | _013_;
  assign _020_ = _040_ | _035_;
  assign _041_ = _019_ & _018_;
  assign _025_ = _041_ & _017_;
  assign _042_[0] = _033_ | slave_select_in;
  assign _019_ = _042_[0] | _042_[1];
  assign _018_ = _042_[0] | _014_;
  assign _024_ = _016_ & _015_;
  assign _037_ = _034_ | _033_;
  assign _043_[1] = slave_select_in | _014_;
  assign _016_ = _037_ | _043_[1];
  assign _017_ = _029_ | slave_select_in;
  assign _015_ = _017_ | _067_[2];
  assign _029_ = _108_ | _067_[1];
  assign _035_ = _032_ |(* src = "src/Slave.v:42.20-42.20|src/Slave.v:35.13-57.20" *)  state[1];
  assign _068_ = state[0] |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _031_;
  assign _044_[0] = _111_[0] &(* src = "src/Slave.v:90.20-90.35" *)  _111_[1];
  assign _012_[1] = _044_[0] &(* src = "src/Slave.v:90.20-90.35" *)  _111_[2];
  assign _045_ = _069_ |(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _070_;
  assign _046_ = _071_ |(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _072_;
  assign _047_ = _073_ |(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _074_;
  assign _048_ = _075_ |(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _076_;
  assign _049_ = _077_ |(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _078_;
  assign _050_ = _079_ |(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _080_;
  assign _051_ = _081_ |(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _082_;
  assign _052_ = _083_ |(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _084_;
  assign _042_[1] = _067_[1] |(* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *)  _067_[2];
  assign _053_ = _085_ |(* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *)  _067_[2];
  assign _054_ = _086_ |(* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *)  _067_[2];
  assign _055_ = _087_ |(* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *)  _067_[2];
  assign _056_ = _067_[2] |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _088_;
  assign _022_ = _067_[2] |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _058_ = _089_ |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _090_;
  assign _059_ = _091_ |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _092_;
  assign _060_ = _093_ |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _094_;
  assign _061_ = _095_ |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _096_;
  assign _062_ = _097_ |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _098_;
  assign _063_ = _099_ |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _100_;
  assign _064_ = _101_ |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _102_;
  assign _065_ = _103_ |(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _104_;
  assign _066_ = state[0] |(* src = "src/Slave.v:35.24-35.24|src/Slave.v:35.13-57.20" *)  state[1];
  assign _067_[1] = ~(* src = "src/Slave.v:42.20-42.20|src/Slave.v:35.13-57.20" *) _035_;
  assign _067_[2] = ~(* src = "src/Slave.v:35.24-35.24|src/Slave.v:35.13-57.20" *) _066_;
  assign _108_ = ~(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _068_;
  assign _010_[0] = _013_ ? (* src = "src/Slave.v:115.12-115.20|src/Slave.v:115.9-115.64" *) sdi : 1'hx;
  assign _010_[1] = _013_ ? (* src = "src/Slave.v:115.12-115.20|src/Slave.v:115.9-115.64" *) shiftreg_rx[0] : 1'hx;
  assign _010_[2] = _013_ ? (* src = "src/Slave.v:115.12-115.20|src/Slave.v:115.9-115.64" *) shiftreg_rx[1] : 1'hx;
  assign _010_[3] = _013_ ? (* src = "src/Slave.v:115.12-115.20|src/Slave.v:115.9-115.64" *) shiftreg_rx[2] : 1'hx;
  assign _010_[4] = _013_ ? (* src = "src/Slave.v:115.12-115.20|src/Slave.v:115.9-115.64" *) shiftreg_rx[3] : 1'hx;
  assign _010_[5] = _013_ ? (* src = "src/Slave.v:115.12-115.20|src/Slave.v:115.9-115.64" *) shiftreg_rx[4] : 1'hx;
  assign _010_[6] = _013_ ? (* src = "src/Slave.v:115.12-115.20|src/Slave.v:115.9-115.64" *) shiftreg_rx[5] : 1'hx;
  assign _010_[7] = _013_ ? (* src = "src/Slave.v:115.12-115.20|src/Slave.v:115.9-115.64" *) shiftreg_rx[6] : 1'hx;
  assign shiftregnext_rx[0] = reset ? (* src = "src/Slave.v:107.8-107.14|src/Slave.v:107.5-122.8" *) _005_[0] : 1'h0;
  assign shiftregnext_rx[1] = reset ? (* src = "src/Slave.v:107.8-107.14|src/Slave.v:107.5-122.8" *) _005_[1] : 1'h0;
  assign shiftregnext_rx[2] = reset ? (* src = "src/Slave.v:107.8-107.14|src/Slave.v:107.5-122.8" *) _005_[2] : 1'h0;
  assign shiftregnext_rx[3] = reset ? (* src = "src/Slave.v:107.8-107.14|src/Slave.v:107.5-122.8" *) _005_[3] : 1'h0;
  assign shiftregnext_rx[4] = reset ? (* src = "src/Slave.v:107.8-107.14|src/Slave.v:107.5-122.8" *) _005_[4] : 1'h0;
  assign shiftregnext_rx[5] = reset ? (* src = "src/Slave.v:107.8-107.14|src/Slave.v:107.5-122.8" *) _005_[5] : 1'h0;
  assign shiftregnext_rx[6] = reset ? (* src = "src/Slave.v:107.8-107.14|src/Slave.v:107.5-122.8" *) _005_[6] : 1'h0;
  assign shiftregnext_rx[7] = reset ? (* src = "src/Slave.v:107.8-107.14|src/Slave.v:107.5-122.8" *) _005_[7] : 1'h0;
  assign _012_[0] = ~(* src = "src/Slave.v:90.20-90.35|src/Slave.v:90.17-91.40" *) _012_[1];
  assign _008_[0] = _068_ ? (* src = "src/Slave.v:92.16-92.16|src/Slave.v:79.13-97.20" *) _012_[0] : 1'h0;
  assign _008_[1] = _068_ ? (* src = "src/Slave.v:92.16-92.16|src/Slave.v:79.13-97.20" *) _012_[1] : 1'h0;
  assign _011_[1] = _068_ ? (* src = "src/Slave.v:92.16-92.16|src/Slave.v:79.13-97.20" *) shiftreg_tx[0] : 1'h0;
  assign _011_[2] = _068_ ? (* src = "src/Slave.v:92.16-92.16|src/Slave.v:79.13-97.20" *) shiftreg_tx[1] : 1'h0;
  assign _011_[3] = _068_ ? (* src = "src/Slave.v:92.16-92.16|src/Slave.v:79.13-97.20" *) shiftreg_tx[2] : 1'h0;
  assign _011_[4] = _068_ ? (* src = "src/Slave.v:92.16-92.16|src/Slave.v:79.13-97.20" *) shiftreg_tx[3] : 1'h0;
  assign _011_[5] = _068_ ? (* src = "src/Slave.v:92.16-92.16|src/Slave.v:79.13-97.20" *) shiftreg_tx[4] : 1'h0;
  assign _011_[6] = _068_ ? (* src = "src/Slave.v:92.16-92.16|src/Slave.v:79.13-97.20" *) shiftreg_tx[5] : 1'h0;
  assign _011_[7] = _068_ ? (* src = "src/Slave.v:92.16-92.16|src/Slave.v:79.13-97.20" *) shiftreg_tx[6] : 1'h0;
  assign _009_ = _035_ ? (* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *) 1'h0 : shiftreg_tx[7];
  assign _003_[0] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _008_[0] : 1'hx;
  assign _003_[1] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _008_[1] : 1'hx;
  assign _002_[0] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _007_[0] : 1'hx;
  assign _002_[1] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _007_[1] : 1'hx;
  assign _002_[2] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _007_[2] : 1'hx;
  assign _006_[0] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) 1'h0 : 1'hx;
  assign _006_[1] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _011_[1] : 1'hx;
  assign _006_[2] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _011_[2] : 1'hx;
  assign _006_[3] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _011_[3] : 1'hx;
  assign _006_[4] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _011_[4] : 1'hx;
  assign _006_[5] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _011_[5] : 1'hx;
  assign _006_[6] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _011_[6] : 1'hx;
  assign _006_[7] = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _011_[7] : 1'hx;
  assign _004_ = _014_ ? (* src = "src/Slave.v:78.12-78.20|src/Slave.v:78.9-99.35" *) _009_ : shiftreg_tx[7];
  assign datacounternext[0] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _002_[0] : 1'h0;
  assign datacounternext[1] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _002_[1] : 1'h0;
  assign datacounternext[2] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _002_[2] : 1'h0;
  assign nextstate[0] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _003_[0] : 1'h0;
  assign nextstate[1] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _003_[1] : 1'h0;
  assign shiftregnext_tx[0] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _006_[0] : 1'h0;
  assign shiftregnext_tx[1] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _006_[1] : 1'h0;
  assign shiftregnext_tx[2] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _006_[2] : 1'h0;
  assign shiftregnext_tx[3] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _006_[3] : 1'h0;
  assign shiftregnext_tx[4] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _006_[4] : 1'h0;
  assign shiftregnext_tx[5] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _006_[5] : 1'h0;
  assign shiftregnext_tx[6] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _006_[6] : 1'h0;
  assign shiftregnext_tx[7] = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _006_[7] : 1'h0;
  assign sdo = reset ? (* src = "src/Slave.v:72.8-72.14|src/Slave.v:72.5-100.8" *) _004_ : 1'h0;
  assign _001_[0] = slave_select_in ? (* src = "src/Slave.v:34.12-34.28|src/Slave.v:34.9-62.12" *) 1'h0 : _107_[0];
  assign _001_[1] = slave_select_in ? (* src = "src/Slave.v:34.12-34.28|src/Slave.v:34.9-62.12" *) 1'h0 : _107_[1];
  assign _109_[0] = _029_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) datacounternext[0] : 1'hx;
  assign _109_[1] = _029_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) datacounternext[1] : 1'hx;
  assign _109_[2] = _029_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) datacounternext[2] : 1'hx;
  assign _000_[0] = slave_select_in ? (* src = "src/Slave.v:34.12-34.28|src/Slave.v:34.9-62.12" *) 1'h1 : _109_[0];
  assign _000_[1] = slave_select_in ? (* src = "src/Slave.v:34.12-34.28|src/Slave.v:34.9-62.12" *) 1'h1 : _109_[1];
  assign _000_[2] = slave_select_in ? (* src = "src/Slave.v:34.12-34.28|src/Slave.v:34.9-62.12" *) 1'h1 : _109_[2];
  assign _069_ = _010_[0] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[1];
  assign _070_ = sdi &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[2];
  assign _071_ = _010_[1] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[1];
  assign _072_ = shiftreg_rx[0] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[2];
  assign _073_ = _010_[2] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[1];
  assign _074_ = shiftreg_rx[1] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[2];
  assign _075_ = _010_[3] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[1];
  assign _076_ = shiftreg_rx[2] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[2];
  assign _077_ = _010_[4] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[1];
  assign _078_ = shiftreg_rx[3] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[2];
  assign _079_ = _010_[5] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[1];
  assign _080_ = shiftreg_rx[4] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[2];
  assign _081_ = _010_[6] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[1];
  assign _082_ = shiftreg_rx[5] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[2];
  assign _083_ = _010_[7] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[1];
  assign _084_ = shiftreg_rx[6] &(* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *)  _067_[2];
  assign _085_ = _111_[0] &(* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *)  _067_[1];
  assign _086_ = _113_[1] &(* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *)  _067_[1];
  assign _087_ = _113_[2] &(* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *)  _067_[1];
  assign _088_ = nextstate[0] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _057_ = nextstate[1] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _089_ = data_in[0] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _067_[2];
  assign _090_ = shiftregnext_tx[0] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _091_ = data_in[1] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _067_[2];
  assign _092_ = shiftregnext_tx[1] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _093_ = data_in[2] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _067_[2];
  assign _094_ = shiftregnext_tx[2] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _095_ = data_in[3] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _067_[2];
  assign _096_ = shiftregnext_tx[3] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _097_ = data_in[4] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _067_[2];
  assign _098_ = shiftregnext_tx[4] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _099_ = data_in[5] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _067_[2];
  assign _100_ = shiftregnext_tx[5] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _101_ = data_in[6] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _067_[2];
  assign _102_ = shiftregnext_tx[6] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _103_ = data_in[7] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _067_[2];
  assign _104_ = shiftregnext_tx[7] &(* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *)  _029_;
  assign _030_ = ~slave_select_in;
  assign _106_ = ~(* src = "src/Slave.v:78.15-78.20" *) sclk;
  assign _105_ = ~(* src = "src/Slave.v:115.12-115.15" *) rx;
  assign _005_[0] = _042_[1] ? (* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *) _045_ : 1'hx;
  assign _005_[1] = _042_[1] ? (* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *) _046_ : 1'hx;
  assign _005_[2] = _042_[1] ? (* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *) _047_ : 1'hx;
  assign _005_[3] = _042_[1] ? (* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *) _048_ : 1'hx;
  assign _005_[4] = _042_[1] ? (* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *) _049_ : 1'hx;
  assign _005_[5] = _042_[1] ? (* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *) _050_ : 1'hx;
  assign _005_[6] = _042_[1] ? (* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *) _051_ : 1'hx;
  assign _005_[7] = _042_[1] ? (* src = "src/Slave.v:113.12-113.12|src/Slave.v:109.5-120.12" *) _052_ : 1'hx;
  assign _007_[0] = _042_[1] ? (* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *) _053_ : 1'hx;
  assign _007_[1] = _042_[1] ? (* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *) _054_ : 1'hx;
  assign _007_[2] = _042_[1] ? (* src = "src/Slave.v:85.16-85.16|src/Slave.v:79.13-97.20" *) _055_ : 1'hx;
  assign _107_[0] = _022_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _056_ : 1'hx;
  assign _107_[1] = _022_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _057_ : 1'hx;
  assign _110_[0] = _022_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _058_ : 1'hx;
  assign _110_[1] = _022_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _059_ : 1'hx;
  assign _110_[2] = _022_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _060_ : 1'hx;
  assign _110_[3] = _022_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _061_ : 1'hx;
  assign _110_[4] = _022_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _062_ : 1'hx;
  assign _110_[5] = _022_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _063_ : 1'hx;
  assign _110_[6] = _022_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _064_ : 1'hx;
  assign _110_[7] = _022_ ? (* src = "src/Slave.v:48.20-48.20|src/Slave.v:35.13-57.20" *) _065_ : 1'hx;
  assign _043_[0] = _037_;
  assign _044_[15:1] = { 14'h3fff, _111_[2] };
  assign { _113_[31:4], _113_[0] } = { _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _113_[3], _111_[0] };
  assign _067_[0] = _033_;
  assign _111_[31:3] = 29'h1fffffff;
  assign { _112_[31:3], _112_[0] } = { _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], _112_[2], datacounter[0] };
  assign _011_[0] = 1'h0;
  assign mode_internal = 2'h0;
endmodule
