/* Generated by Yosys 0.65 (git sha1 90c26fe6714b441363d2ddb47a6d646b8868ff5d, g++ 16.1.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "Master.v:5.1-190.10" *)
module Master(data_in, slave_select_in, mode, clkin, reset, tx_enable, miso, data_out, sclk, mosi, slave_select);
  (* src = "Master.v:7.22-7.29" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "Master.v:8.22-8.37" *)
  input [1:0] slave_select_in;
  wire [1:0] slave_select_in;
  (* src = "Master.v:8.39-8.43" *)
  input [1:0] mode;
  wire [1:0] mode;
  (* src = "Master.v:9.16-9.21" *)
  input clkin;
  wire clkin;
  (* src = "Master.v:9.23-9.28" *)
  input reset;
  wire reset;
  (* src = "Master.v:9.30-9.39" *)
  input tx_enable;
  wire tx_enable;
  (* src = "Master.v:9.41-9.45" *)
  input miso;
  wire miso;
  (* src = "Master.v:13.22-13.30" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "Master.v:16.16-16.20" *)
  output sclk;
  wire sclk;
  (* src = "Master.v:16.22-16.26" *)
  output mosi;
  wire mosi;
  (* src = "Master.v:17.22-17.34" *)
  output [3:0] slave_select;
  wire [3:0] slave_select;
  (* src = "Master.v:40.1-85.4" *)
  wire [2:0] _000_;
  (* src = "Master.v:40.1-85.4" *)
  wire _001_;
  (* src = "Master.v:94.1-143.4" *)
  wire [2:0] _002_;
  (* src = "Master.v:94.1-143.4" *)
  wire [1:0] _003_;
  (* src = "Master.v:146.1-156.4" *)
  wire _004_;
  (* src = "Master.v:94.1-143.4" *)
  wire [7:0] _005_;
  (* src = "Master.v:159.1-184.4" *)
  wire [7:0] _006_;
  (* src = "Master.v:94.1-143.4" *)
  wire [3:0] _007_;
  (* src = "Master.v:94.1-143.4" *)
  wire [2:0] _008_;
  (* src = "Master.v:94.1-143.4" *)
  wire _009_;
  (* src = "Master.v:146.1-156.4" *)
  wire _010_;
  (* src = "Master.v:94.1-143.4" *)
  wire [7:0] _011_;
  (* src = "Master.v:159.1-184.4" *)
  wire [7:0] _012_;
  (* src = "Master.v:94.1-143.4" *)
  wire [3:0] _013_;
  (* src = "Master.v:94.1-143.4" *)
  wire [1:0] _014_;
  (* src = "Master.v:159.1-184.4" *)
  wire [7:0] _015_;
  (* src = "Master.v:94.1-143.4" *)
  wire [3:0] _016_;
  (* src = "Master.v:159.1-184.4" *)
  wire [7:0] _017_;
  (* src = "Master.v:110.13-110.49" *)
  wire [3:0] _018_;
  (* src = "Master.v:168.16-168.24" *)
  wire _019_;
  (* src = "Master.v:174.16-174.24" *)
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire [15:0] _043_;
  wire [15:0] _044_;
  wire [7:0] _045_;
  wire [2:0] _046_;
  wire _047_;
  wire [1:0] _048_;
  wire _049_;
  wire [1:0] _050_;
  wire _051_;
  wire _052_;
  wire [1:0] _053_;
  wire [1:0] _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire [2:0] _086_;
  wire [3:0] _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  (* src = "Master.v:52.13-52.27" *)
  wire _134_;
  (* src = "Master.v:168.19-168.24" *)
  wire _135_;
  (* src = "Master.v:174.16-174.19" *)
  wire _136_;
  wire _137_;
  (* force_downto = 32'd1 *)
  (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:135.22-135.23" *)
  wire [2:0] _138_;
  (* force_downto = 32'd1 *)
  (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:137.23-137.24" *)
  wire [3:0] _139_;
  (* force_downto = 32'd1 *)
  (* src = "Master.v:121.12-121.24|Master.v:52.13-52.27|/usr/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _140_;
  (* force_downto = 32'd1 *)
  (* src = "Master.v:52.13-52.27|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _141_;
  (* force_downto = 32'd1 *)
  (* src = "Master.v:52.13-52.27|/usr/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _142_;
  (* force_downto = 32'd1 *)
  (* src = "Master.v:52.13-52.27|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _143_;
  (* force_downto = 32'd1 *)
  (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [2:0] _144_;
  (* force_downto = 32'd1 *)
  (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [2:0] _145_;
  (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:157.2-184.5" *)
  wire [7:0] _146_;
  (* force_downto = 32'd1 *)
  (* src = "Master.v:122.31-122.45|Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _147_;
  (* force_downto = 32'd1 *)
  (* src = "Master.v:122.31-122.45|Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _148_;
  (* src = "Master.v:52.13-52.27|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _149_;
  (* src = "Master.v:122.31-122.45|Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _150_;
  (* src = "Master.v:32.11-32.23" *)
  reg [2:0] counter_sclk;
  (* src = "Master.v:32.25-32.35" *)
  reg [2:0] data_count;
  (* src = "Master.v:33.29-33.42" *)
  reg [1:0] mode_internal;
  (* src = "Master.v:35.5-35.7" *)
  reg rx;
  (* src = "Master.v:34.5-34.18" *)
  reg sclk_internal;
  (* src = "Master.v:31.11-31.19" *)
  reg [7:0] shiftreg;
  (* src = "Master.v:31.35-31.46" *)
  reg [7:0] shiftreg_rx;
  (* src = "Master.v:31.48-31.63" *)
  wire [7:0] shiftregnext_rx;
  (* src = "Master.v:33.11-33.16" *)
  reg [1:0] state;
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) counter_sclk[0] <= 1'h0;
    else counter_sclk[0] <= _000_[0];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) counter_sclk[1] <= 1'h0;
    else counter_sclk[1] <= _000_[1];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) counter_sclk[2] <= 1'h1;
    else counter_sclk[2] <= _000_[2];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) rx <= 1'h0;
    else rx <= _001_;
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin)
    if (_032_) data_count[0] <= _002_[0];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin)
    if (_032_) data_count[1] <= _002_[1];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin)
    if (_032_) data_count[2] <= _002_[2];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg[0] <= 1'h0;
    else if (_031_) shiftreg[0] <= _005_[0];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg[1] <= 1'h0;
    else if (_031_) shiftreg[1] <= _005_[1];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg[2] <= 1'h0;
    else if (_031_) shiftreg[2] <= _005_[2];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg[3] <= 1'h0;
    else if (_031_) shiftreg[3] <= _005_[3];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg[4] <= 1'h0;
    else if (_031_) shiftreg[4] <= _005_[4];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg[5] <= 1'h0;
    else if (_031_) shiftreg[5] <= _005_[5];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg[6] <= 1'h0;
    else if (_031_) shiftreg[6] <= _005_[6];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg[7] <= 1'h0;
    else if (_031_) shiftreg[7] <= _005_[7];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[0] <= 1'h0;
    else if (_030_) shiftreg_rx[0] <= shiftregnext_rx[0];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[1] <= 1'h0;
    else if (_030_) shiftreg_rx[1] <= shiftregnext_rx[1];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[2] <= 1'h0;
    else if (_030_) shiftreg_rx[2] <= shiftregnext_rx[2];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[3] <= 1'h0;
    else if (_030_) shiftreg_rx[3] <= shiftregnext_rx[3];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[4] <= 1'h0;
    else if (_030_) shiftreg_rx[4] <= shiftregnext_rx[4];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[5] <= 1'h0;
    else if (_030_) shiftreg_rx[5] <= shiftregnext_rx[5];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[6] <= 1'h0;
    else if (_030_) shiftreg_rx[6] <= shiftregnext_rx[6];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) shiftreg_rx[7] <= 1'h0;
    else if (_030_) shiftreg_rx[7] <= shiftregnext_rx[7];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[0] <= 1'h0;
    else if (_029_) data_out[0] <= shiftreg_rx[0];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[1] <= 1'h0;
    else if (_029_) data_out[1] <= shiftreg_rx[1];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[2] <= 1'h0;
    else if (_029_) data_out[2] <= shiftreg_rx[2];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[3] <= 1'h0;
    else if (_029_) data_out[3] <= shiftreg_rx[3];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[4] <= 1'h0;
    else if (_029_) data_out[4] <= shiftreg_rx[4];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[5] <= 1'h0;
    else if (_029_) data_out[5] <= shiftreg_rx[5];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[6] <= 1'h0;
    else if (_029_) data_out[6] <= shiftreg_rx[6];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) data_out[7] <= 1'h0;
    else if (_029_) data_out[7] <= shiftreg_rx[7];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) sclk_internal <= 1'h0;
    else if (!_134_) sclk_internal <= _035_;
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) mode_internal[0] <= 1'h0;
    else if (_028_) mode_internal[0] <= mode[0];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) mode_internal[1] <= 1'h0;
    else if (_028_) mode_internal[1] <= mode[1];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) state[0] <= 1'h0;
    else if (_027_) state[0] <= _003_[0];
  (* src = "Master.v:40.1-85.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) state[1] <= 1'h0;
    else if (_027_) state[1] <= _003_[1];
  assign _140_[2] = ~data_count[2];
  assign _140_[1] = ~data_count[1];
  assign _142_[1] = ~counter_sclk[1];
  assign _142_[2] = ~counter_sclk[2];
  assign _140_[0] = ~data_count[0];
  assign _143_[0] = ~counter_sclk[0];
  assign _037_ = ~state[1];
  assign _038_ = ~state[0];
  assign _040_ = ~reset;
  assign _041_ = ~_087_[1];
  assign _138_[2] = ~_145_[1];
  assign _143_[3] = ~_141_[2];
  assign _036_ = _143_[3] | _045_[0];
  assign _143_[1] = _142_[1] ^(* src = "Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  counter_sclk[0];
  assign _143_[2] = _142_[2] ^(* src = "Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  _141_[1];
  assign _148_[1] = _140_[1] ^(* src = "Master.v:122.31-122.45|Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  data_count[0];
  assign _148_[2] = _140_[2] ^(* src = "Master.v:122.31-122.45|Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  _147_[1];
  assign _138_[1] = _144_[1] ^(* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:296.13-296.25" *)  _144_[0];
  assign _149_ = _142_[2] &(* src = "Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _141_[1];
  assign _141_[2] = counter_sclk[2] |(* src = "Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _149_;
  assign _141_[1] = counter_sclk[1] |(* src = "Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _044_[0];
  assign _147_[1] = data_count[1] |(* src = "Master.v:122.31-122.45|Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _150_;
  assign _150_ = _140_[1] &(* src = "Master.v:122.31-122.45|Master.v:52.45-52.59|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  data_count[0];
  assign _145_[1] = _144_[1] &(* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:293.27-293.63|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _144_[0];
  assign _019_ = rx &(* src = "Master.v:168.16-168.24" *)  _135_;
  assign _020_ = _136_ &(* src = "Master.v:174.16-174.24" *)  sclk;
  assign _039_ = _038_ |(* src = "Master.v:66.12-66.12|Master.v:60.9-83.16" *)  state[1];
  assign _088_ = state[0] |(* src = "Master.v:72.12-72.12|Master.v:60.9-83.16" *)  _037_;
  assign _043_[0] = _140_[0] &(* src = "Master.v:121.12-121.24|Master.v:52.13-52.27" *)  _140_[1];
  assign _014_[1] = _043_[0] &(* src = "Master.v:121.12-121.24|Master.v:52.13-52.27" *)  _140_[2];
  assign _044_[0] = counter_sclk[0] &(* src = "Master.v:52.13-52.27" *)  _142_[1];
  assign _045_[0] = _044_[0] &(* src = "Master.v:52.13-52.27" *)  _142_[2];
  assign _046_[0] = _026_ & _025_;
  assign _046_[2] = _033_ & reset;
  assign _047_ = _046_[0] & _046_[1];
  assign _032_ = _047_ & _046_[2];
  assign _026_ = _014_[0] | _039_;
  assign _048_[0] = _025_ & _024_;
  assign _049_ = _048_[0] & _046_[1];
  assign _031_ = _049_ & _033_;
  assign _024_ = tx_enable | _042_;
  assign _050_[0] = _023_ & _022_;
  assign _050_[1] = _021_ & _036_;
  assign _051_ = _050_[0] & _050_[1];
  assign _030_ = _051_ & _033_;
  assign _052_ = _040_ | _086_[1];
  assign _023_ = _052_ | _086_[2];
  assign _053_[0] = _040_ | _041_;
  assign _053_[1] = _019_ | _039_;
  assign _022_ = _053_[0] | _053_[1];
  assign _054_[0] = _040_ | _087_[1];
  assign _054_[1] = _020_ | _039_;
  assign _021_ = _054_[0] | _054_[1];
  assign _029_ = _036_ & _137_;
  assign _055_ = _036_ & sclk_internal;
  assign _028_ = _055_ & _137_;
  assign _046_[1] = _036_ & _035_;
  assign _027_ = _046_[1] & _033_;
  assign _033_ = _025_ | _137_;
  assign _087_[1] = mode_internal[0] ^(* src = "Master.v:166.12-166.26" *)  mode_internal[1];
  assign _085_ = _132_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _133_;
  assign _056_ = _089_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _090_;
  assign _057_ = _091_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _092_;
  assign _025_ = _086_[1] |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _058_ = _093_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _059_ = _094_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _060_ = _095_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _042_ = state[0] |(* src = "Master.v:60.20-60.20|Master.v:60.9-83.16" *)  state[1];
  assign _061_ = _096_ |(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _097_;
  assign _062_ = _098_ |(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _099_;
  assign _063_ = _100_ |(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _101_;
  assign _064_ = _102_ |(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _103_;
  assign _065_ = _104_ |(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _105_;
  assign _066_ = _106_ |(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _107_;
  assign _067_ = _108_ |(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _109_;
  assign _068_ = _110_ |(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _111_;
  assign _069_ = _086_[2] |(* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *)  _034_;
  assign _070_ = _086_[2] |(* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *)  _112_;
  assign _071_ = _086_[2] |(* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *)  _113_;
  assign _072_ = _086_[2] |(* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *)  _114_;
  assign _073_ = _086_[2] |(* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *)  _115_;
  assign _034_ = _137_ |(* src = "Master.v:127.8-127.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _077_ = _116_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _117_;
  assign _078_ = _118_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _119_;
  assign _079_ = _120_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _121_;
  assign _080_ = _122_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _123_;
  assign _081_ = _124_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _125_;
  assign _082_ = _126_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _127_;
  assign _083_ = _128_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _129_;
  assign _084_ = _130_ |(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _131_;
  assign _086_[1] = ~(* src = "Master.v:66.12-66.12|Master.v:60.9-83.16" *) _039_;
  assign _086_[2] = ~(* src = "Master.v:60.20-60.20|Master.v:60.9-83.16" *) _042_;
  assign _137_ = ~(* src = "Master.v:72.12-72.12|Master.v:60.9-83.16" *) _088_;
  assign _009_ = _039_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) 1'h0 : shiftreg[7];
  assign slave_select[0] = sclk_internal ? (* src = "Master.v:103.8-103.22|Master.v:103.5-142.8" *) _016_[0] : _007_[0];
  assign slave_select[1] = sclk_internal ? (* src = "Master.v:103.8-103.22|Master.v:103.5-142.8" *) _016_[1] : _007_[1];
  assign slave_select[2] = sclk_internal ? (* src = "Master.v:103.8-103.22|Master.v:103.5-142.8" *) _016_[2] : _007_[2];
  assign slave_select[3] = sclk_internal ? (* src = "Master.v:103.8-103.22|Master.v:103.5-142.8" *) _016_[3] : _007_[3];
  assign mosi = sclk_internal ? (* src = "Master.v:103.8-103.22|Master.v:103.5-142.8" *) shiftreg[7] : _009_;
  assign _000_[0] = _036_ ? (* src = "Master.v:52.13-52.27|Master.v:52.10-84.8" *) 1'h0 : _143_[0];
  assign _000_[1] = _036_ ? (* src = "Master.v:52.13-52.27|Master.v:52.10-84.8" *) 1'h0 : _143_[1];
  assign _000_[2] = _036_ ? (* src = "Master.v:52.13-52.27|Master.v:52.10-84.8" *) 1'h1 : _143_[2];
  assign _001_ = _036_ ? (* src = "Master.v:52.13-52.27|Master.v:52.10-84.8" *) sclk : sclk_internal;
  assign _146_[0] = slave_select_in[0] ? (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:178.4-183.7|/usr/bin/../share/yosys/techmap.v:178.8-178.12" *) 1'h0 : _145_[1];
  assign _146_[3] = slave_select_in[0] ? (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:178.4-183.7|/usr/bin/../share/yosys/techmap.v:178.8-178.12" *) _138_[2] : 1'h0;
  assign _146_[4] = slave_select_in[0] ? (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:178.4-183.7|/usr/bin/../share/yosys/techmap.v:178.8-178.12" *) 1'h0 : _138_[2];
  assign _139_[0] = _138_[1] ? (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:178.4-183.7|/usr/bin/../share/yosys/techmap.v:178.8-178.12" *) 1'h0 : _146_[0];
  assign _139_[1] = _138_[1] ? (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:178.4-183.7|/usr/bin/../share/yosys/techmap.v:178.8-178.12" *) _146_[3] : 1'h0;
  assign _139_[2] = _138_[1] ? (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:178.4-183.7|/usr/bin/../share/yosys/techmap.v:178.8-178.12" *) _146_[4] : 1'h0;
  assign _139_[3] = _138_[1] ? (* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:178.4-183.7|/usr/bin/../share/yosys/techmap.v:178.8-178.12" *) 1'h0 : _146_[3];
  assign _017_[0] = _020_ ? (* src = "Master.v:174.16-174.24|Master.v:174.13-176.16" *) miso : 1'hx;
  assign _017_[1] = _020_ ? (* src = "Master.v:174.16-174.24|Master.v:174.13-176.16" *) shiftreg_rx[0] : 1'hx;
  assign _017_[2] = _020_ ? (* src = "Master.v:174.16-174.24|Master.v:174.13-176.16" *) shiftreg_rx[1] : 1'hx;
  assign _017_[3] = _020_ ? (* src = "Master.v:174.16-174.24|Master.v:174.13-176.16" *) shiftreg_rx[2] : 1'hx;
  assign _017_[4] = _020_ ? (* src = "Master.v:174.16-174.24|Master.v:174.13-176.16" *) shiftreg_rx[3] : 1'hx;
  assign _017_[5] = _020_ ? (* src = "Master.v:174.16-174.24|Master.v:174.13-176.16" *) shiftreg_rx[4] : 1'hx;
  assign _017_[6] = _020_ ? (* src = "Master.v:174.16-174.24|Master.v:174.13-176.16" *) shiftreg_rx[5] : 1'hx;
  assign _017_[7] = _020_ ? (* src = "Master.v:174.16-174.24|Master.v:174.13-176.16" *) shiftreg_rx[6] : 1'hx;
  assign _015_[0] = _019_ ? (* src = "Master.v:168.16-168.24|Master.v:168.13-170.16" *) miso : 1'hx;
  assign _015_[1] = _019_ ? (* src = "Master.v:168.16-168.24|Master.v:168.13-170.16" *) shiftreg_rx[0] : 1'hx;
  assign _015_[2] = _019_ ? (* src = "Master.v:168.16-168.24|Master.v:168.13-170.16" *) shiftreg_rx[1] : 1'hx;
  assign _015_[3] = _019_ ? (* src = "Master.v:168.16-168.24|Master.v:168.13-170.16" *) shiftreg_rx[2] : 1'hx;
  assign _015_[4] = _019_ ? (* src = "Master.v:168.16-168.24|Master.v:168.13-170.16" *) shiftreg_rx[3] : 1'hx;
  assign _015_[5] = _019_ ? (* src = "Master.v:168.16-168.24|Master.v:168.13-170.16" *) shiftreg_rx[4] : 1'hx;
  assign _015_[6] = _019_ ? (* src = "Master.v:168.16-168.24|Master.v:168.13-170.16" *) shiftreg_rx[5] : 1'hx;
  assign _015_[7] = _019_ ? (* src = "Master.v:168.16-168.24|Master.v:168.13-170.16" *) shiftreg_rx[6] : 1'hx;
  assign _012_[0] = _087_[1] ? (* src = "Master.v:166.12-166.26|Master.v:166.9-177.12" *) _015_[0] : _017_[0];
  assign _012_[1] = _087_[1] ? (* src = "Master.v:166.12-166.26|Master.v:166.9-177.12" *) _015_[1] : _017_[1];
  assign _012_[2] = _087_[1] ? (* src = "Master.v:166.12-166.26|Master.v:166.9-177.12" *) _015_[2] : _017_[2];
  assign _012_[3] = _087_[1] ? (* src = "Master.v:166.12-166.26|Master.v:166.9-177.12" *) _015_[3] : _017_[3];
  assign _012_[4] = _087_[1] ? (* src = "Master.v:166.12-166.26|Master.v:166.9-177.12" *) _015_[4] : _017_[4];
  assign _012_[5] = _087_[1] ? (* src = "Master.v:166.12-166.26|Master.v:166.9-177.12" *) _015_[5] : _017_[5];
  assign _012_[6] = _087_[1] ? (* src = "Master.v:166.12-166.26|Master.v:166.9-177.12" *) _015_[6] : _017_[6];
  assign _012_[7] = _087_[1] ? (* src = "Master.v:166.12-166.26|Master.v:166.9-177.12" *) _015_[7] : _017_[7];
  assign shiftregnext_rx[0] = reset ? (* src = "Master.v:161.4-161.10|Master.v:161.1-183.4" *) _006_[0] : 1'h0;
  assign shiftregnext_rx[1] = reset ? (* src = "Master.v:161.4-161.10|Master.v:161.1-183.4" *) _006_[1] : 1'h0;
  assign shiftregnext_rx[2] = reset ? (* src = "Master.v:161.4-161.10|Master.v:161.1-183.4" *) _006_[2] : 1'h0;
  assign shiftregnext_rx[3] = reset ? (* src = "Master.v:161.4-161.10|Master.v:161.1-183.4" *) _006_[3] : 1'h0;
  assign shiftregnext_rx[4] = reset ? (* src = "Master.v:161.4-161.10|Master.v:161.1-183.4" *) _006_[4] : 1'h0;
  assign shiftregnext_rx[5] = reset ? (* src = "Master.v:161.4-161.10|Master.v:161.1-183.4" *) _006_[5] : 1'h0;
  assign shiftregnext_rx[6] = reset ? (* src = "Master.v:161.4-161.10|Master.v:161.1-183.4" *) _006_[6] : 1'h0;
  assign shiftregnext_rx[7] = reset ? (* src = "Master.v:161.4-161.10|Master.v:161.1-183.4" *) _006_[7] : 1'h0;
  assign _010_ = _087_[1] ? (* src = "Master.v:152.16-152.30|Master.v:152.13-153.40" *) sclk_internal : _035_;
  assign _004_ = _039_ ? (* src = "Master.v:151.12-151.29|Master.v:151.9-154.12" *) mode_internal[1] : _010_;
  assign sclk = reset ? (* src = "Master.v:148.8-148.14|Master.v:148.5-155.8" *) _004_ : 1'h0;
  assign _014_[0] = ~(* src = "Master.v:121.12-121.24|Master.v:121.9-125.31" *) _014_[1];
  assign _008_[0] = _014_[1] ? (* src = "Master.v:121.12-121.24|Master.v:121.9-125.31" *) 1'hx : _140_[0];
  assign _008_[1] = _014_[1] ? (* src = "Master.v:121.12-121.24|Master.v:121.9-125.31" *) 1'hx : _148_[1];
  assign _008_[2] = _014_[1] ? (* src = "Master.v:121.12-121.24|Master.v:121.9-125.31" *) 1'hx : _148_[2];
  assign _013_[0] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) _018_[0] : 1'h1;
  assign _013_[1] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) _018_[1] : 1'h1;
  assign _013_[2] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) _018_[2] : 1'h1;
  assign _013_[3] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) _018_[3] : 1'h1;
  assign _011_[0] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) data_in[0] : 1'hx;
  assign _011_[1] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) data_in[1] : 1'hx;
  assign _011_[2] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) data_in[2] : 1'hx;
  assign _011_[3] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) data_in[3] : 1'hx;
  assign _011_[4] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) data_in[4] : 1'hx;
  assign _011_[5] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) data_in[5] : 1'hx;
  assign _011_[6] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) data_in[6] : 1'hx;
  assign _011_[7] = tx_enable ? (* src = "Master.v:107.12-107.21|Master.v:107.9-116.12" *) data_in[7] : 1'hx;
  assign _089_ = _018_[2] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _090_ = _013_[2] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _091_ = _018_[3] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _092_ = _013_[3] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _093_ = _008_[0] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _094_ = _008_[1] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _095_ = _008_[2] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _096_ = _012_[0] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[1];
  assign _097_ = miso &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[2];
  assign _098_ = _012_[1] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[1];
  assign _099_ = shiftreg_rx[0] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[2];
  assign _100_ = _012_[2] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[1];
  assign _101_ = shiftreg_rx[1] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[2];
  assign _102_ = _012_[3] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[1];
  assign _103_ = shiftreg_rx[2] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[2];
  assign _104_ = _012_[4] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[1];
  assign _105_ = shiftreg_rx[3] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[2];
  assign _106_ = _012_[5] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[1];
  assign _107_ = shiftreg_rx[4] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[2];
  assign _108_ = _012_[6] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[1];
  assign _109_ = shiftreg_rx[5] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[2];
  assign _110_ = _012_[7] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[1];
  assign _111_ = shiftreg_rx[6] &(* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *)  _086_[2];
  assign _112_ = _018_[0] &(* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *)  _034_;
  assign _113_ = _018_[1] &(* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *)  _034_;
  assign _114_ = _018_[2] &(* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *)  _034_;
  assign _115_ = _018_[3] &(* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *)  _034_;
  assign _074_ = _014_[0] &(* src = "Master.v:127.8-127.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _075_ = _014_[1] &(* src = "Master.v:127.8-127.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _076_ = _011_[0] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _116_ = shiftreg[0] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _117_ = _011_[1] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _118_ = shiftreg[1] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _119_ = _011_[2] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _120_ = shiftreg[2] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _121_ = _011_[3] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _122_ = shiftreg[3] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _123_ = _011_[4] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _124_ = shiftreg[4] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _125_ = _011_[5] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _126_ = shiftreg[5] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _127_ = _011_[6] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _128_ = shiftreg[6] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _129_ = _011_[7] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _130_ = _018_[0] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _131_ = _013_[0] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _132_ = _018_[1] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[1];
  assign _133_ = _013_[1] &(* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *)  _086_[2];
  assign _134_ = ~(* src = "Master.v:52.13-52.27" *) _036_;
  assign _144_[0] = ~(* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) slave_select_in[0];
  assign _144_[1] = ~(* src = "Master.v:140.14-140.50|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) slave_select_in[1];
  assign _035_ = ~sclk_internal;
  assign _018_[0] = ~(* src = "Master.v:140.14-140.50" *) _139_[0];
  assign _018_[1] = ~(* src = "Master.v:140.14-140.50" *) _139_[1];
  assign _018_[2] = ~(* src = "Master.v:140.14-140.50" *) _139_[2];
  assign _018_[3] = ~(* src = "Master.v:140.14-140.50" *) _139_[3];
  assign _135_ = ~(* src = "Master.v:168.19-168.24" *) sclk;
  assign _136_ = ~(* src = "Master.v:174.16-174.19" *) rx;
  assign _007_[1] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _085_ : 1'h1;
  assign _007_[2] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _056_ : 1'h1;
  assign _007_[3] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _057_ : 1'h1;
  assign _002_[0] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _058_ : 1'hx;
  assign _002_[1] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _059_ : 1'hx;
  assign _002_[2] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _060_ : 1'hx;
  assign _006_[0] = _025_ ? (* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *) _061_ : 1'hx;
  assign _006_[1] = _025_ ? (* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *) _062_ : 1'hx;
  assign _006_[2] = _025_ ? (* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *) _063_ : 1'hx;
  assign _006_[3] = _025_ ? (* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *) _064_ : 1'hx;
  assign _006_[4] = _025_ ? (* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *) _065_ : 1'hx;
  assign _006_[5] = _025_ ? (* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *) _066_ : 1'hx;
  assign _006_[6] = _025_ ? (* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *) _067_ : 1'hx;
  assign _006_[7] = _025_ ? (* src = "Master.v:164.54-164.54|Master.v:163.5-182.12" *) _068_ : 1'hx;
  assign _016_[0] = _069_ ? (* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *) _070_ : 1'h1;
  assign _016_[1] = _069_ ? (* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *) _071_ : 1'h1;
  assign _016_[2] = _069_ ? (* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *) _072_ : 1'h1;
  assign _016_[3] = _069_ ? (* src = "Master.v:139.56-139.56|Master.v:137.9-141.16" *) _073_ : 1'h1;
  assign _003_[0] = _034_ ? (* src = "Master.v:127.8-127.8|Master.v:104.5-133.12" *) _074_ : tx_enable;
  assign _003_[1] = _034_ ? (* src = "Master.v:127.8-127.8|Master.v:104.5-133.12" *) _075_ : 1'h0;
  assign _005_[0] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _076_ : 1'hx;
  assign _005_[1] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _077_ : 1'hx;
  assign _005_[2] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _078_ : 1'hx;
  assign _005_[3] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _079_ : 1'hx;
  assign _005_[4] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _080_ : 1'hx;
  assign _005_[5] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _081_ : 1'hx;
  assign _005_[6] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _082_ : 1'hx;
  assign _005_[7] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _083_ : 1'hx;
  assign _007_[0] = _025_ ? (* src = "Master.v:117.8-117.8|Master.v:104.5-133.12" *) _084_ : 1'h1;
  assign _043_[15:1] = { 14'h3fff, _140_[2] };
  assign _044_[15:1] = { 14'h3fff, _142_[2] };
  assign { _145_[2], _145_[0] } = { _145_[1], _144_[0] };
  assign _138_[0] = slave_select_in[0];
  assign { _142_[31:3], _142_[0] } = { 29'h1fffffff, counter_sclk[0] };
  assign { _146_[7:5], _146_[2:1] } = 5'h00;
  assign _144_[2] = 1'h1;
  assign { _148_[31:4], _148_[0] } = { _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _148_[3], _140_[0] };
  assign _140_[31:3] = 29'h1fffffff;
  assign { _141_[31:3], _141_[0] } = { _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], _141_[2], counter_sclk[0] };
  assign { _147_[31:3], _147_[0] } = { _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], _147_[2], data_count[0] };
  assign { _087_[3:2], _087_[0] } = { _039_, _020_, _040_ };
  assign _045_[7:1] = 7'h7f;
  assign _086_[0] = _040_;
  assign _143_[31:4] = { _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3], _143_[3] };
  assign _048_[1] = _046_[1];
endmodule
